"""init two tables

Revision ID: 3ad86eeed847
Revises: 
Create Date: 2019-05-05 22:26:11.203186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad86eeed847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(length=32), nullable=False),
    sa.Column('machines_model', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=16), nullable=True),
    sa.Column('part_number', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('part_name', sa.String(length=128), nullable=True),
    sa.Column('where_is_part', sa.String(length=32), nullable=True),
    sa.Column('exchange_status', sa.String(length=32), nullable=True),
    sa.Column('janome_status', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('customer_delivery_time', sa.String(length=32), nullable=True),
    sa.Column('delivery_time', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_customer_delivery_time'), 'issues', ['customer_delivery_time'], unique=False)
    op.create_index(op.f('ix_issues_delivery_time'), 'issues', ['delivery_time'], unique=False)
    op.create_index(op.f('ix_issues_exchange_status'), 'issues', ['exchange_status'], unique=False)
    op.create_index(op.f('ix_issues_janome_status'), 'issues', ['janome_status'], unique=False)
    op.create_index(op.f('ix_issues_machines_model'), 'issues', ['machines_model'], unique=False)
    op.create_index(op.f('ix_issues_part_name'), 'issues', ['part_name'], unique=False)
    op.create_index(op.f('ix_issues_part_number'), 'issues', ['part_number'], unique=False)
    op.create_index(op.f('ix_issues_time_stamp'), 'issues', ['time_stamp'], unique=False)
    op.create_index(op.f('ix_issues_where_is_part'), 'issues', ['where_is_part'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_where_is_part'), table_name='issues')
    op.drop_index(op.f('ix_issues_time_stamp'), table_name='issues')
    op.drop_index(op.f('ix_issues_part_number'), table_name='issues')
    op.drop_index(op.f('ix_issues_part_name'), table_name='issues')
    op.drop_index(op.f('ix_issues_machines_model'), table_name='issues')
    op.drop_index(op.f('ix_issues_janome_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_exchange_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_delivery_time'), table_name='issues')
    op.drop_index(op.f('ix_issues_customer_delivery_time'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
