"""added issue desc column

Revision ID: 58de1a450dc8
Revises: 3ad86eeed847
Create Date: 2019-05-07 19:58:05.429199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58de1a450dc8'
down_revision = '3ad86eeed847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('issue_desc', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'issue_desc')
    # ### end Alembic commands ###
